<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Vadim Titkov</Authors>
    <Description>Provides seamless integration with HashiCorp Vault for .NET configuration system, allowing secure retrieval of application secrets. Supports multiple authentication methods and flexible configuration options for accessing Vault secrets.</Description>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <PackageProjectUrl>https://github.com/itvadim/hcv.config</PackageProjectUrl>
    <PackageTags>Vault;HashiCorp;Configuration;Secrets</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/itvadim/hcv.config.git</RepositoryUrl>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DocumentationFile>bin\Release\T100.Extensions.Configuration.HashiCorpVault.Secrets.xml</DocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="VaultSharp" Version="1.17.5.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="T100.Extensions.Configuration.HashiCorpVault.Secrets.UnitTests"/>
  </ItemGroup>

</Project>
